create or replace PROCEDURE SP_PAGAR_PRESTAMO_ATRASADO(
    P_ID_PRESTAMO VARCHAR2,
    P_MENSAJE OUT VARCHAR2)
AS
   V_CUOTA DECIMAL;
    V_ID_FORMA_PAGO INTEGER;
    V_PLAZO_MESES INTEGER;
    V_CANTIDAD_CUOTAS INTEGER;
    V_FECHA_FINAL DATE;
    V_FECHA_PAGAR DATE;
    V_CANTIDAD_DIAS INTEGER;
    V_SALDO_ACTUAL DECIMAL;
    V_TASA_INTERES DECIMAL;
    V_CONTADOR_CUOTAS INTEGER;
    V_CUOTA_SIN_INTERES DECIMAL;
BEGIN
  SELECT CUOTA, ID_FORMA_PAGO, PLAZO_MESES, TASA_INTERES
        INTO V_CUOTA, V_ID_FORMA_PAGO, V_PLAZO_MESES, V_TASA_INTERES
  FROM TBL_PRESTAMOS
  WHERE (ID_PRESTAMO=P_ID_PRESTAMO);
  V_CUOTA_SIN_INTERES:=V_CUOTA;
  SELECT COUNT(*) INTO V_CANTIDAD_CUOTAS
  FROM TBL_DESCRIPCION_PRESTAMOS
  WHERE (ID_PRESTAMO=P_ID_PRESTAMO);
  IF (V_ID_FORMA_PAGO=1) THEN
    SELECT A.SALDO_ACTUAL INTO V_SALDO_ACTUAL 
    FROM TBL_DESCRIPCION_PRESTAMOS A 
    WHERE A.FECHA_PAGO= ( SELECT MAX(FECHA_PAGO)  FROM TBL_DESCRIPCION_PRESTAMOS WHERE ID_PRESTAMO=P_ID_PRESTAMO) 
      AND  ID_PRESTAMO=P_ID_PRESTAMO; 
    V_CANTIDAD_DIAS:= V_FECHA_FINAL-SYSDATE;
    V_CUOTA:=(V_CUOTA*V_CANTIDAD_DIAS*-1*((V_TASA_INTERES/100)+1));
    INSERT
    INTO TBL_DESCRIPCION_PRESTAMOS
      (
        ID_DESCRIPCION_PRESTAMO,
        ID_PRESTAMO,
        ID_EMPLEADO,
        FECHA_PAGO,
        PAGO,
        SALDO_ACTUAL,
        ID_TIPO_CUOTA
      )
      VALUES
      (
        SEQ_DESCRIPCION_PRESTAMO.NEXTVAL,
        P_ID_PRESTAMO,
        NULL,
        SYSDATE,
        V_CUOTA,
        0,
        2
      );
      UPDATE TBL_PRESTAMOS
      SET ID_ESTADO_PRESTAMO = 2
      WHERE ID_PRESTAMO = P_ID_PRESTAMO;
      COMMIT;
  ELSE
  
    V_CONTADOR_CUOTAS:=1;
    SELECT FECHA_INICIAL INTO V_FECHA_PAGAR
    FROM TBL_PRESTAMOS WHERE ID_PRESTAMO=P_ID_PRESTAMO;
    
    WHILE (V_CONTADOR_CUOTAS!=V_PLAZO_MESES) LOOP
      V_FECHA_PAGAR:=ADD_MONTHS(V_FECHA_PAGAR,1);
      V_CONTADOR_CUOTAS:=V_CONTADOR_CUOTAS+1;
    END LOOP;
    V_FECHA_PAGAR:=ADD_MONTHS(V_FECHA_PAGAR,1);
    SELECT A.SALDO_ACTUAL INTO V_SALDO_ACTUAL 
    FROM TBL_DESCRIPCION_PRESTAMOS A 
    WHERE A.FECHA_PAGO= ( SELECT MAX(FECHA_PAGO)  FROM TBL_DESCRIPCION_PRESTAMOS WHERE ID_PRESTAMO=P_ID_PRESTAMO) 
      AND  ID_PRESTAMO=P_ID_PRESTAMO; 
    V_CUOTA:=(V_CUOTA*MONTHS_BETWEEN(SYSDATE,V_FECHA_PAGAR)*-1*(V_TASA_INTERES+1));
    V_SALDO_ACTUAL:=V_SALDO_ACTUAL-V_CUOTA_SIN_INTERES;
    INSERT
    INTO TBL_DESCRIPCION_PRESTAMOS
      (
        ID_DESCRIPCION_PRESTAMO,
        ID_PRESTAMO,
        ID_EMPLEADO,
        FECHA_PAGO,
        PAGO,
        SALDO_ACTUAL,
        ID_TIPO_CUOTA
      )
      VALUES
      (
        SEQ_DESCRIPCION_PRESTAMO.NEXTVAL,
        P_ID_PRESTAMO,
        NULL,
        SYSDATE,
        V_CUOTA,
        V_SALDO_ACTUAL,
        2
      );
      SELECT COUNT(*) INTO V_CANTIDAD_CUOTAS
      FROM TBL_DESCRIPCION_PRESTAMOS
      WHERE (ID_PRESTAMO=P_ID_PRESTAMO);
      IF (V_CANTIDAD_CUOTAS>=V_PLAZO_MESES)THEN
        UPDATE TBL_PRESTAMOS
        SET ID_ESTADO_PRESTAMO = 2
        WHERE ID_PRESTAMO = P_ID_PRESTAMO;
      END IF;
      COMMIT;
  END IF;
EXCEPTION 
    WHEN OTHERS THEN 
      P_MENSAJE:='ERROR: '||SQLCODE||SQLERRM;
      ROLLBACK;
END;