CREATE SEQUENCE SEQ_CLIENTE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_DIRECCION
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_EMPRESA
INCREMENT BY 1
START WITH 1
;
CREATE SEQUENCE SEQ_CUENTA_AHORRO
INCREMENT BY 1
START WITH 1
;

CREATE SEQUENCE SEQ_DETALLE_CUENTA_AHORRO
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_INFORMACION_PROYECTO
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_INFORMACION_PRESTAMO
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_INFORMACION_GARANTIA
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_NUMERO_SOLICITUD
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_NUMERO_PRESTAMO
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_DECISION_JUNTA
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_DESCRIPCION_PRESTAMO
INCREMENT BY 1
START WITH 1;

