create or replace PROCEDURE SP_ACTUALIZAR_CLIENTE(
      P_ID_CLIENTE VARCHAR2,
      P_ID_ESTADO_CIVIL INTEGER,
      P_ID_PROFESION INTEGER,
      P_ID_DIRECCION INTEGER,
      P_ID_EMPRESA INTEGER,
      P_ID_CARGO INTEGER,
      P_NUMERO_IDENTIDAD VARCHAR2,
      P_NOMBRES VARCHAR2,
      P_APELLIDOS VARCHAR2,
      P_TELEFONO VARCHAR2,
      P_CELULAR VARCHAR2,
      P_SALARIO NUMBER,
      P_CORREO_ELECTRONICO VARCHAR2,
      P_GENERO CHAR,
      P_FECHA_NACIMIENTO DATE,
      P_MENSAJE OUT VARCHAR2
  )AS
      V_NUMERO_MUNICIPIO INTEGER;
      V_EDAD INTEGER;
  BEGIN
  
    SELECT trunc((trunc(SYSDATE) - trunc(to_date(P_FECHA_NACIMIENTO,'DD/MM/YYYY')))/365) INTO V_EDAD from dual;

   IF V_EDAD>=0 THEN BEGIN 
      UPDATE TBL_CLIENTES
      SET ID_ESTADO_CIVIL=P_ID_ESTADO_CIVIL,
          ID_PROFESION = P_ID_PROFESION,
          ID_DIRECCION = P_ID_DIRECCION,
          ID_EMPRESA = P_ID_EMPRESA,
          ID_CARGO= P_ID_CARGO,
          NUMERO_IDENTIDAD=P_NUMERO_IDENTIDAD,
          NOMBRES=P_NOMBRES,
          APELLIDOS=P_APELLIDOS,
          TELEFONO=P_TELEFONO,
          CELULAR=P_CELULAR,
          SALARIO=P_SALARIO,
          CORREO_ELECTRONICO=P_CORREO_ELECTRONICO,
          GENERO=P_GENERO,
          FECHA_NACIMIENTO=P_FECHA_NACIMIENTO
      WHERE ID_CLIENTE= P_ID_CLIENTE;
       COMMIT;        
                 
         P_MENSAJE:= 'ACTUALIZADO CON EXITO: ';
      END;
      ELSE
        P_MENSAJE:= 'ERROR ES MENOR DE EDAD';
      END IF;
        EXCEPTION 
          WHEN OTHERS THEN 
           P_MENSAJE:='ERROR: '||SQLCODE||SQLERRM;
            ROLLBACK;
        END;