create or replace PROCEDURE SP_DIRECCION(
      P_ID_COLONIA INTEGER,
      P_DESCRIPCION_DIRECCION VARCHAR2,
      P_MENSAJE OUT VARCHAR2
  )AS
     P_NUMERO_SECUENCIA INTEGER;
  BEGIN
     P_NUMERO_SECUENCIA:=SEQ_DIRECCION.NEXTVAL;
    INSERT
      INTO TBL_DIRECCIONES
        (
          ID_DIRECCION,
          DESCRIPCION_DIRECCION,
          ID_COLONIA
        )
        VALUES
        (
          P_NUMERO_SECUENCIA,
          UPPER(P_DESCRIPCION_DIRECCION),
          P_ID_COLONIA
        );
      COMMIT;
     P_MENSAJE:= P_NUMERO_SECUENCIA;
    EXCEPTION 
      WHEN OTHERS THEN 
       P_MENSAJE:='ERROR: '||SQLCODE||SQLERRM;
        ROLLBACK;
    END;