create or replace PROCEDURE SP_BUSCAR_CLIENTE_SOLICITUD(
    P_ID_CLIENTE VARCHAR2,
    P_NOMBRE_PROYECTO OUT VARCHAR2,
    P_DESCRIPCION OUT VARCHAR2,
    P_ID_TIPO_GARANTIA OUT INTEGER, 
    P_NOMBRE_COMPLETO_AVAL1 OUT VARCHAR2,
    P_NUMERO_IDENTIDAD_AVAL1 OUT VARCHAR2,
    P_TELEFONO_AVAL1 OUT VARCHAR2, 
    P_CELULAR_AVAL1 OUT VARCHAR2,
    P_DIRECCION_AVAL1 OUT VARCHAR2,
    P_NOMBRE_COMPLETO_AVAL2 OUT VARCHAR2,
    P_NUMERO_IDENTIDAD_AVAL2 OUT VARCHAR2,
    P_TELEFONO_AVAL2 OUT VARCHAR2, 
    P_CELULAR_AVAL2 OUT VARCHAR2,
    P_DIRECCION_AVAL2 OUT VARCHAR2,
    P_DESCRIPCION_GARANTIA OUT VARCHAR2,
    P_MENSAJE OUT VARCHAR2
    )
AS
  V_CANTIDAD_CLIENTE INTEGER;
  V_EXISTE_CLIENTE INTEGER;
  V_ID_SOLICITUD VARCHAR2(12);
  V_NOMBRES_CLIENTE VARCHAR(300);
  V_APELLIDOS_CLIENTE VARCHAR(300);
BEGIN
   SELECT COUNT(*) INTO V_CANTIDAD_CLIENTE
    FROM TBL_CLIENTES_X_SOLICITUDES
    WHERE ID_CLIENTE= P_ID_CLIENTE;
    
  SELECT COUNT(*) INTO V_EXISTE_CLIENTE 
  FROM TBL_CLIENTES WHERE ID_CLIENTE= P_ID_CLIENTE;
  
  IF(V_EXISTE_CLIENTE>0)THEN
      IF (V_CANTIDAD_CLIENTE>0 )THEN 
        SELECT A.ID_SOLICITUD INTO V_ID_SOLICITUD 
        FROM TBL_CLIENTES_X_SOLICITUDES A
        INNER JOIN TBL_SOLICITUDES B
          ON(A.ID_SOLICITUD=B.ID_SOLICITUD)
        WHERE B.FECHA_SOLICITUD=( SELECT MAX(FECHA_SOLICITUD)FROM TBL_CLIENTES_X_SOLICITUDES F
                                    INNER JOIN TBL_SOLICITUDES G
                                    ON(F.ID_SOLICITUD=G.ID_SOLICITUD)
                                    WHERE F.ID_CLIENTE=  P_ID_CLIENTE) 
              AND A.ID_CLIENTE = P_ID_CLIENTE;
                                    
        SELECT B.NOMBRE_PROYECTO, B.DESCRIPCION, C.ID_TIPO_GARANTIA, C.NOMBRE_COMPLETO_AVAL1, C.NUMERO_IDENTIDAD_AVAL1,C.TELEFONO_AVAL1, C.CELULAR_AVAL1,C.DIRECCION_AVAL1,
        C.NOMBRE_COMPLETO_AVAL2, C.NUMERO_IDENTIDAD_AVAL2,C.TELEFONO_AVAL2, C.CELULAR_AVAL2,C.DIRECCION_AVAL2,C.DESCRIPCION_GARANTIA
        INTO P_NOMBRE_PROYECTO, P_DESCRIPCION, P_ID_TIPO_GARANTIA, P_NOMBRE_COMPLETO_AVAL1,P_NUMERO_IDENTIDAD_AVAL1, P_TELEFONO_AVAL1, P_CELULAR_AVAL1, P_DIRECCION_AVAL1,
        P_NOMBRE_COMPLETO_AVAL2,P_NUMERO_IDENTIDAD_AVAL2, P_TELEFONO_AVAL2, P_CELULAR_AVAL2, P_DIRECCION_AVAL2,P_DESCRIPCION_GARANTIA
        FROM TBL_SOLICITUDES A
        INNER JOIN TBL_INFORMACION_PROYECTOS B
          ON(A.ID_INFORMACION_PROYECTO=B.ID_INFORMACION_PROYECTO)
        INNER JOIN TBL_INFORMACION_GARANTIAS C
          ON(A.ID_INFORMACION_GARANTIA=C.ID_INFORMACION_GARANTIA)
        WHERE V_ID_SOLICITUD= A.ID_SOLICITUD;
      END IF;
      SELECT C.NOMBRES, APELLIDOS INTO V_NOMBRES_CLIENTE, V_APELLIDOS_CLIENTE 
      FROM TBL_CLIENTES C
      WHERE ID_CLIENTE = P_ID_CLIENTE;
      P_MENSAJE:=V_NOMBRES_CLIENTE||' '||V_APELLIDOS_CLIENTE;
  ELSE
    P_MENSAJE:='ERROR: EL CLIENTE NO EXISTE';
  END IF;
EXCEPTION 
    WHEN OTHERS THEN 
      P_MENSAJE:='ERROR: '||SQLCODE||SQLERRM;
      ROLLBACK;
END;